#!/bin/bash

readonly go1="1.10.1"

echo "------------------------------"
echo "Running go module"
echo "------------------------------"
echo ""

brew bundle install -v --file="./brewfile"

echo "------------------------------"
goenv init

if [[ -z "${SMU_ZSH_DIR+x}" ]]; then
    echo "It looks like you are not using the set-me-up terminal module."
    echo "Please follow the goenv instructions above (generated by the command 'rbenv init') to complete the installation."
    read -n 1 -s -r -p "Press any key to continue."
    echo ""
fi

echo "------------------------------"
echo "Installing go ${go1} and setting as global version"

goenv install "${go1}" -s
goenv global "${go1}"

goenv rehash
