#!/bin/bash

readonly node8=${node8:-"8.11.1"}
readonly node10=${node10:-"10.0.0"}

echo "------------------------------"
echo "Running web module"
echo "------------------------------"
echo ""

echo "------------------------------"
echo "Installing brew dependencies"

brew bundle install -v --file="./brewfile"

echo "------------------------------"
nodenv init

if [[ -z "${SMU_ZSH_DIR+x}" ]]; then
    echo "It looks like you are not using the set-me-up terminal module."
    echo "Please follow the nodenv instructions above (generated by the command 'nodenv init') to complete the installation."
    read -n 1 -s -r -p "Press any key to continue."
    echo ""
fi


echo "------------------------------"
echo "Installing node ${node8}"

nodenv install "${node8}" -s

echo "------------------------------"
echo "Installing node ${node10} and setting as global version"

nodenv install "${node10}" -s
nodenv global "${node10}"

nodenv rehash

